import os

MQTT_HOST = os.environ.get("MQTT_HOST", "localhost")
MQTT_PORT = int(os.environ.get("MQTT_PORT", "8883"))

# TLS + per-drone auth (Sprint 11) - each drone connects as its own
# username ("drone-1", "drone-2", ...) built from its external_id, sharing
# one password (the fleet's single trust tier) since generating/distributing
# genuinely distinct per-unit secrets is out of scope for this project.
# ca_cert_path defaults to the host-relative location generated by
# infra/mosquitto/setup/generate.sh, matching how the backend resolves it.
MQTT_USE_TLS = os.environ.get("MQTT_USE_TLS", "true").lower() != "false"
MQTT_CA_CERT_PATH = os.environ.get("MQTT_CA_CERT_PATH", "../infra/mosquitto/certs/ca.crt")
MQTT_DRONE_PASSWORD = os.environ.get("MQTT_DRONE_PASSWORD", "changeme")

DRONE_COUNT = int(os.environ.get("DRONE_COUNT", "4"))
PUBLISH_INTERVAL_SECONDS = float(os.environ.get("PUBLISH_INTERVAL_SECONDS", "2"))

# How many publish ticks it takes a drone to cross one leg of its patrol
# route - lower is faster/choppier movement, higher is slower/smoother.
TICKS_PER_SEGMENT = int(os.environ.get("TICKS_PER_SEGMENT", "10"))

BATTERY_DRAIN_PER_TICK = float(os.environ.get("BATTERY_DRAIN_PER_TICK", "0.5"))
LOW_BATTERY_THRESHOLD = float(os.environ.get("LOW_BATTERY_THRESHOLD", "20"))

# Sprint 12: injected into published telemetry only - the true simulated
# position (route progress, waypoint/mission arrival) is never affected,
# only what gets reported over MQTT, the same way a real drone's actual
# position and its noisy GPS reading of that position are two different
# things. 5m matches typical civilian GPS accuracy. Converted from meters
# to degrees using a fixed ~111,320 m/degree - accurate enough at this
# demo's small scale and roughly fixed latitude (Madrid), not meant to
# hold globally.
GPS_NOISE_STD_METERS = float(os.environ.get("GPS_NOISE_STD_METERS", "5.0"))
GPS_NOISE_STD_DEGREES = GPS_NOISE_STD_METERS / 111_320.0

# Sprint 13: simulates a dropped radio connection, not a dropped GPS fix -
# unlike GPS noise, this suppresses publishing entirely for a while rather
# than corrupting what's published. A drone keeps flying (and draining
# battery/completing missions) while "out of contact" - only the backend
# loses track of it, exactly like a real field unit that's still airborne
# behind a hill with no line of sight to its ground station. Per-tick
# chance of 0.01 at the default 2s publish interval is roughly one outage
# every ~200s per drone; a 5-15 tick duration is a 10-30s outage, long
# enough to be clearly visible (SIGNAL_LOST persisting for several backend
# watchdog ticks) without stalling a demo for minutes.
SIGNAL_LOSS_CHANCE_PER_TICK = float(os.environ.get("SIGNAL_LOSS_CHANCE_PER_TICK", "0.01"))
SIGNAL_LOSS_MIN_TICKS = int(os.environ.get("SIGNAL_LOSS_MIN_TICKS", "5"))
SIGNAL_LOSS_MAX_TICKS = int(os.environ.get("SIGNAL_LOSS_MAX_TICKS", "15"))

# Sprint 14: the two halves of "swarm mode" - patrolling movement becomes
# boids flocking instead of each drone's own fixed square route, and idle
# (PATROLLING) drones bid on missions/available instead of waiting for a
# direct centralized assignment. Pair with the backend's own
# swarmhq.mission-assignment.mode=auction - the bidding half of this flag
# does nothing on its own if the backend is still deciding centrally, and
# vice versa an auction with SWARM_MODE=false backends just never gets bids.
SWARM_MODE = os.environ.get("SWARM_MODE", "false").lower() == "true"

# Degrees, not meters, throughout - boids.py works directly in lat/lon
# space (see its own module docstring for the longitude-scaling reasoning),
# so these are already the right unit for BoidsParams without conversion.
BOIDS_NEIGHBOR_RADIUS_DEGREES = float(os.environ.get("BOIDS_NEIGHBOR_RADIUS_DEGREES", "0.02"))
BOIDS_SEPARATION_WEIGHT = float(os.environ.get("BOIDS_SEPARATION_WEIGHT", "1.5"))
BOIDS_ALIGNMENT_WEIGHT = float(os.environ.get("BOIDS_ALIGNMENT_WEIGHT", "1.0"))
BOIDS_COHESION_WEIGHT = float(os.environ.get("BOIDS_COHESION_WEIGHT", "1.0"))
# Gentle on purpose - just enough to keep the flock from wandering off
# indefinitely, not so strong it overrides separation/alignment/cohesion
# and collapses the flock onto a single point.
BOIDS_CENTER_WEIGHT = float(os.environ.get("BOIDS_CENTER_WEIGHT", "0.5"))
# ~0.0008 deg/tick is comparable to the original fixed-route patrol speed
# (a 0.006 deg square side over TICKS_PER_SEGMENT=10 ticks, ~0.0006 deg/tick)
# - similar pace, not a race and not a crawl.
BOIDS_MAX_STEP_DEGREES = float(os.environ.get("BOIDS_MAX_STEP_DEGREES", "0.0008"))
