import os

MQTT_HOST = os.environ.get("MQTT_HOST", "localhost")
MQTT_PORT = int(os.environ.get("MQTT_PORT", "8883"))

# TLS + per-drone auth (Sprint 11) - each drone connects as its own
# username ("drone-1", "drone-2", ...) built from its external_id, sharing
# one password (the fleet's single trust tier) since generating/distributing
# genuinely distinct per-unit secrets is out of scope for this project.
# ca_cert_path defaults to the host-relative location generated by
# infra/mosquitto/setup/generate.sh, matching how the backend resolves it.
MQTT_USE_TLS = os.environ.get("MQTT_USE_TLS", "true").lower() != "false"
MQTT_CA_CERT_PATH = os.environ.get("MQTT_CA_CERT_PATH", "../infra/mosquitto/certs/ca.crt")
MQTT_DRONE_PASSWORD = os.environ.get("MQTT_DRONE_PASSWORD", "changeme")

DRONE_COUNT = int(os.environ.get("DRONE_COUNT", "4"))
PUBLISH_INTERVAL_SECONDS = float(os.environ.get("PUBLISH_INTERVAL_SECONDS", "2"))

# How many publish ticks it takes a drone to cross one leg of its patrol
# route - lower is faster/choppier movement, higher is slower/smoother.
TICKS_PER_SEGMENT = int(os.environ.get("TICKS_PER_SEGMENT", "10"))

BATTERY_DRAIN_PER_TICK = float(os.environ.get("BATTERY_DRAIN_PER_TICK", "0.5"))
LOW_BATTERY_THRESHOLD = float(os.environ.get("LOW_BATTERY_THRESHOLD", "20"))

# Sprint 12: injected into published telemetry only - the true simulated
# position (route progress, waypoint/mission arrival) is never affected,
# only what gets reported over MQTT, the same way a real drone's actual
# position and its noisy GPS reading of that position are two different
# things. 5m matches typical civilian GPS accuracy. Converted from meters
# to degrees using a fixed ~111,320 m/degree - accurate enough at this
# demo's small scale and roughly fixed latitude (Madrid), not meant to
# hold globally.
GPS_NOISE_STD_METERS = float(os.environ.get("GPS_NOISE_STD_METERS", "5.0"))
GPS_NOISE_STD_DEGREES = GPS_NOISE_STD_METERS / 111_320.0
