package com.swarmhq.model;

public enum EventType {
    LOW_BATTERY,
    WAYPOINT_REACHED,
    SIGNAL_LOST,
    SIGNAL_RECOVERED,
    STATUS_CHANGE,
    ENTERED_RISK_ZONE,
    EXITED_RISK_ZONE,
    MISSION_FAILED,
    MISSION_CANCELLED
}
