CREATE TABLE drones (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type            VARCHAR(50) NOT NULL,
    position        GEOMETRY(Point, 4326),
    battery_percent INTEGER NOT NULL,
    status          VARCHAR(20) NOT NULL,
    last_update_at  TIMESTAMPTZ NOT NULL
);

CREATE TABLE missions (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    route             GEOMETRY(LineString, 4326) NOT NULL,
    assigned_drone_id BIGINT REFERENCES drones (id),
    status            VARCHAR(20) NOT NULL,
    priority          VARCHAR(10) NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE events (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    drone_id    BIGINT NOT NULL REFERENCES drones (id),
    mission_id  BIGINT REFERENCES missions (id),
    type        VARCHAR(30) NOT NULL,
    detail      VARCHAR(500),
    occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_drones_position ON drones USING GIST (position);
CREATE INDEX idx_missions_route ON missions USING GIST (route);
CREATE INDEX idx_events_drone_id ON events (drone_id);
CREATE INDEX idx_events_mission_id ON events (mission_id);
