CREATE TABLE risk_zones (
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    area GEOMETRY(Polygon, 4326) NOT NULL
);

CREATE INDEX idx_risk_zones_area ON risk_zones USING GIST (area);

-- Straddles the western leg of drone-1's patrol square (simulator/routes.py:
-- base (40.4168, -3.7038), side 0.006 deg - that edge runs along
-- lon = -3.7038 from lat 40.4168 to 40.4228), so the demo simulator
-- actually walks a drone through this zone every patrol loop instead of
-- requiring manually-crafted telemetry to see the alert fire.
INSERT INTO risk_zones (name, area) VALUES (
    'Sector 1 Perimeter Risk Zone',
    ST_GeomFromText('POLYGON((-3.7048 40.4190, -3.7028 40.4190, -3.7028 40.4210, -3.7048 40.4210, -3.7048 40.4190))', 4326)
);
